version: '3.7'

services:
  db:
      image: postgres
      container_name: "postgres_test_app"
      command: -p 54320
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_NAME}
      ports:
        - "${DATABASE_PORT}:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: 'test_app'
    command: bash -c "${RUN_API}"
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    depends_on:
      - db
  redis:
    image: redis
    container_name: 'redis'
    command: redis-server
    ports:
      - '6379:6379'
  celery-beat:
    build: .
    container_name: 'celery-beat'
    command: celery -A test_proj beat -l DEBUG
    volumes:
      - .:/app
    depends_on:
      - redis
      - web
volumes:
    postgres_data: