# Generated by Django 3.1.3 on 2020-11-12 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=21, unique=True)),
                ('author', models.CharField(max_length=50)),
                ('tags', models.TextField(max_length=300)),
                ('image_file', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
